### ISSUE TITLE
Enum-Mapping.md is outdated

### ISSUE THREAD

**Issue by starkmsu** [AutoMapper/AutoMapper.Extensions.EnumMapping#3] opened 2020-04-07 19:40 UTC
https://github.com/AutoMapper/AutoMapper/blob/master/docs/Enum-Mapping.md contents are outdated.
This nugget package is missing - https://www.nuget.org/packages/AutoMapper.Extensions.EnumMapping/

**Comment by lbargaoanu** [comment] 2020-04-08 04:50
Duplicate of #2.

**Closed by lbargaoanu** 2020-04-08 04:50 UTC
